name: Deploy to apitable

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: check key
      run: |
        echo ${{secrets.SSH_PRIVATE_KEY}}
        sudo apt-get update
        sudo apt-get install ansible
    - name: env
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
    - name: Deploy to apitable
      uses: dawidd6/action-ansible-playbook@v2.5.0
      with:
        # Required, playbook filepath
        playbook: run.yml
        # Optional, directory where playbooks live
        directory: ./apitable/ansible
        # Optional, SSH private key
        key: ${{secrets.SSH_PRIVATE_KEY}}
        # Optional, SSH known hosts file content
        known_hosts: .known_hosts
        # Optional, additional flags to pass to ansible-playbook
        options: |
          --inventory hosts
          --extra-vars hello=there
          --verbose
