name: sync-apitable-enterprise

on:
  push:
    tags:
      - "v*"
    branches:
      - "v*"
  workflow_dispatch:

jobs:
  sync-apitable-enterprise:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Checkout apitable-enterprise
        uses: actions/checkout@v2
        with:
          repository: paylm/CircleCI-enterprise
          ref: ${{ env.GITHUB_REPOSITORY }}
          token: ${{ secrets.CR_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: ./.git/CircleCI-enterprise
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Sync to CircleCI  Enterprise
        run: |
          rsync -av --exclude='.github/workflows/copy-enterprise.yml' --exclude='.git/' --exclude='ai/' ./.git/CircleCI-enterprise
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'release: APITable Enterprise'
