name: sync-apitable-enterprise

on:
  push:
    tags:
      - "v*"
    branches:
      - "v*"
  workflow_dispatch:

jobs:
  sync-apitable-enterprise:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Checkout apitable-enterprise
        uses: actions/checkout@v2
        with:
          repository: paylm/CircleCI-enterprise
          token: ${{ secrets.CR_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: ./.git/CircleCI-enterprise
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Sync to CircleCI  Enterprise
        run: |
          echo "bracn ${GITHUB_REF_NAME}"
          cd ./.git/CircleCI-enterprise  && git checkout -b ${GITHUB_REF_NAME} && git pull && cd -
          rsync -av --exclude='.github/workflows/copy-enterprise.yml' --exclude='.git/' --exclude='ai/' ./ ./.git/CircleCI-enterprise
          ls -a ./.git/CircleCI-enterprise
          ls ./
          cd ./.git/CircleCI-enterprise && git status && cd -
      - name: Set commit message  
        id: commit_message_step
        run: |
          echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
          echo "release: APITable Enterprise on ${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
          repository: ./.git/CircleCI-enterprise
          create_branch: true
          branch: ${{ github.ref_name }}
