name: test

on:
  push:
    branches:
      - "main"
      - "test/**"
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "init-appdata/**"
  workflow_dispatch:
  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Running Build
        shell: bash
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          MYSQL_HOST: 123
          MYSQL_PORT: 3306
        run: |
          env | grep MYSQL > .env
          echo "check env values"
          cat .env
      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.23.0
          helmv3: 3.7.2
          command: helm version && kubectl version
