name: Vika deploy

# 参考： actions/using-workflows/events-that-trigger-workflows#repository_dispatch
#
# {
#  "event_type": "deploy",
#  "client_payload": {
#    "edition": vika,   产品： vika or apitable
#    "env": "integration" 环境
#    "app": "backend-server" 服务
#    "containerName": "backend-server" 容器名
#    "image": "docker.vikadata.com/vikadata/vika/backend-server:latest-alpha" 镜像
#    "replicas": 1
#  }
#}
#
#
on:
  repository_dispatch:
    types: [deploy]
jobs:
  deploy-vika:
    if: ${{ github.event.action == 'deploy' }}
    runs-on: ubuntu-latest
    name: ${{ github.event.client_payload.edition }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: GIT commit and push all changed files
#        env:
#          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
#          CI_COMMIT_AUTHOR: Continuous Integration
#        run: bash commit.sh ${{ github.event.client_payload.app }} ${{ github.event.client_payload.containerName }} ${{ github.event.client_payload.image }} ${{ github.event.client_payload.env }} ${{ github.event.client_payload.edition }}
#
#
      - name: deploy k8s
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_VIKA_CONFIG }}
        with:
          args: whoami

      - name: deploy k8s 2
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_VIKA_CONFIG }}
        with:
          args: |
            echo "${{ github.event.client_payload.app }}"
            [ "${{ github.event.client_payload.env }}" == "production" ] && echo "deploy release"

  deploy-apitable:
    name: apitable ${{ github.event.client_payload.app }} ${{ github.event.client_payload.SEMVER_FULL}}
    runs-on: ubuntu-latest
    if: ${{ github.event_type == 'deploy' && github.event.client_payload.edition == 'apitable' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: deploy k8s apitable
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_VIKA_CONFIG }}
        with:
          args: whoami
#      - name: deploy k8s
#        uses: wahyd4/kubectl-helm-action@master
#        env:
#          KUBE_CONFIG_DATA: ${{ secrets.KUBE_VIKA_CONFIG }}
#        with:
#          args: whoami && kubectl get pods
  deploy-prod:
    runs-on: ubuntu-latest
    name:  ${{ github.event.client_payload.app }} - ${{ github.event.client_payload.SEMVER_FULL}}
    #    environment:
    #      name: production
    #      url: https://integration.vika.ltd/workbench?spaceId=spczdmQDfBAn5

    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.CR_PAT }}
          approvers: paylm
          issue-title: Deploying ${{ github.event.client_payload.app }} ${{ github.event.client_payload.SEMVER_FULL}} to production
      - name: Checkout
        uses: actions/checkout@v3
      - name: check key
        run: |
          echo ${{ inputs.tags }}
          echo  ${{ github.event.client_payload.edition }}
          echo ${{ github.event_type == 'deploy' }}
          pwd
  #      - name: deploy k8s
  #        uses: wahyd4/kubectl-helm-action@master
  #        env:
  #          KUBE_CONFIG_DATA: ${{ secrets.KUBE_VIKA_CONFIG }}
  #        with:
  #          args: whoami && kubectl get pods

  deploy-default:
    runs-on: ubuntu-latest
    name:  ${{ github.event.client_payload.app }} - ${{ github.event.client_payload.SEMVER_FULL}}
#    environment:
#      name: production
#      url: https://integration.vika.ltd/workbench?spaceId=spczdmQDfBAn5

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: trstringer/manual-approval@v1
        if: ${{ contains(github.event.client_payload.SEMVER_FULL,'release.') }}
        with:
         secret: ${{ secrets.CR_PAT }}
         approvers: paylm
         minimum-approvals: 0
         issue-title: Deploying ${{ github.event.client_payload.app }} ${{ github.event.client_payload.SEMVER_FULL}} to production
      - name: Checkout
        uses: actions/checkout@v3
      - name: check key
        run: |
          echo ${{ inputs.tags }}
          echo  ${{ github.event.client_payload.edition }}
          echo ${{ github.event_type == 'deploy' }}
          pwd
#      - name: deploy k8s
#        uses: wahyd4/kubectl-helm-action@master
#        env:
#          KUBE_CONFIG_DATA: ${{ secrets.KUBE_VIKA_CONFIG }}
#        with:
#          args: whoami && kubectl get pods

